name: Sync Repositories

on:
  schedule:
    - cron: '0 12 * * *' # 每天运行一次
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: Savantank/RuleList
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0

    - name: Checkout ios_rule_script repository
      uses: actions/checkout@v2
      with:
        repository: blackmatrix7/ios_rule_script
        path: temp_ios_rule_script
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Checkout ProxyResource repository
      uses: actions/checkout@v2
      with:
        repository: luestr/ProxyResource
        path: temp_ProxyResource
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Checkout ddgksf2013 repository
      uses: actions/checkout@v2
      with:
        repository: ddgksf2013/ddgksf2013
        path: temp_ddgksf2013
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Checkout Orz-3 repository
      uses: actions/checkout@v2
      with:
        repository: Orz-3/mini
        path: temp_Orz3_mini
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Sync ios_rule_script to bm7 folder
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        rm -rf bm7
        mkdir -p bm7
        cp -r temp_ios_rule_script/* bm7/
        git add bm7
        git commit -m 'Sync ios_rule_script to bm7 folder'

    - name: Sync ProxyResource to iKeLee folder
      run: |
        rm -rf iKeLee
        mkdir -p iKeLee
        cp -r temp_ProxyResource/* iKeLee/
        git add iKeLee
        git commit -m 'Sync ProxyResource to iKeLee folder'

    - name: Sync ddgksf2013 to 墨鱼配置 folder
      run: |
        rm -rf 墨鱼配置
        mkdir -p 墨鱼配置
        cp -r temp_ddgksf2013/* 墨鱼配置/
        git add 墨鱼配置
        git commit -m 'Sync ddgksf2013 to 墨鱼配置 folder'

    - name: Sync Orz-3 mini to 小白图标 folder
      run: |
        rm -rf 小白图标
        mkdir -p 小白图标
        cp -r temp_Orz3_mini/* 小白图标/
        git add 小白图标
        git commit -m 'Sync Orz-3 mini to 小白图标 folder'

    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
